//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Car.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public class Car extends Train {

	private Train prevTrain;

	public void Car(int x, int y, int xE, int yE) {
	}
	
	public void getOffPassengers() {
	}
	
	public Train getPrevTrain() {
		return null;
	}
	
	public void setPrevTrain(Train t) {
	}
}
