//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Engine.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public class Engine extends Train {

	public void Engine(int x, int y, int xE, int yE) {

	}
}
