//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MapItem.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public abstract class MapItem {

	private int x;
	private int y;

	public int getX() {
		return 0;
	}
	
	public int getY() {
		return 0;
	}
}
