//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Model.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public class Model{

	private Station[] stations;
	private Switch[] switches;
	private TunnelEntrance[] tunnelEntrances;
	private Rail[] rails;
	private Engine[] engines;
	private Car[] cars;

	public void Model() {
	}
	
	public Status moveEngines() {
		return null;
	}
	
	public void addTrainToMap(int numberOfCars) {
	}
	
	public void decideActions(int x1, int y1, int x2, int y2) {
	}
	
	private void addTunnelEntrance(int x1, int y1, int x2, int y2) {
	}
	
	private void removeTunnelEntrance(TunnelEntrance tE) {
	}
	
	private void changeSwitch(Switch s) {
	}
	
	private void removeTrain(Train trainPart) {
	}
	
	private boolean isMapEmpty() {
		return false;
	}
}
