//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Model.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

import java.util.ArrayList;
import java.util.List;

public class Model{

	private List<Station> stations;
	private List<Switch> switches;
	private List<TunnelEntrance> tunnelEntrances;
	private List<Rail> rails;
	private List<Engine> engines;
	private List<Car> cars;

	public Model() {
        this.engines = new ArrayList<Engine>();
	}
	
	public Status moveEngines() {
            Main.tabs++;
            Status temp = Status.NOT_CRASHED;
            System.out.print(">");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("->[:Model].moveEngines()\n");

            engines.add(new Engine(1,1,1,2)); 

            for(int i = 0; i < engines.size(); i++) {
                if ( engines.get(i).move() == Status.CRASHED) temp = Status.CRASHED;
            }

            System.out.print("<");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("<-[:Model].moveEngines()\n");
                
            return temp;      
	}
	
	public void addTrainToMap(int numberOfCars) {
	}
	
	public void decideActions(int x1, int y1, int x2, int y2) {
	}
	
	private void addTunnelEntrance(int x1, int y1, int x2, int y2) {
	}
	
	private void removeTunnelEntrance(TunnelEntrance tE) {
	}
	
	private void changeSwitch(Switch s) {
	}
	
	private void removeTrain(Train trainPart) {
	}
	
	private boolean isMapEmpty() {
		return false;
	}
}
