//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Model.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public class Model{

	private Station[] stations;
	private Switch[] switches;
	private TunnelEntrance[] tunnelEntrances;
	private Rail[] rails;
	private Engine[] engines;
	private Car[] cars;

	public void Model() {
	}
	
	public Status moveEngines() {
		System.out.print(">");
		for(int i = 0; i <= Main.tabs; i++) {
			System.out.print("\t");
		}
		System.out.println("->[:Model].moveEngines()");

		System.out.print('?');
		for(int i = 0; i <= Main.tabs; i++) {
			System.out.print("\t");
		}
		System.out.print("6.1. Van még vonat a pályán? I/N: ");

		char c = 0;
		try{
			c = (char) System.in.read();
		} catch(Exception e) {
			e.printStackTrace();
		}

		if (c == 'N' || c == 'n'){
			System.out.print('?');

			for(int i = 0; i <= Main.tabs; i++) {
				System.out.print("\t");
			}
			System.out.print("6.2. Lesz még vonat a pályán? I/N: ");
			char ch = 0;
			try{
				System.in.read();
				ch = (char) System.in.read();
			} catch(Exception e) {
				e.printStackTrace();
			}

		}

		System.out.print("<");

		for(int i = 0; i <= Main.tabs; i++) {
			System.out.print("\t");
		}
		System.out.print("<-[:Model].moveEngines()\n");
		Main.tabs--;

		return null;
	}
	
	public void addTrainToMap(int numberOfCars) {
	}
	
	public void decideActions(int x1, int y1, int x2, int y2) {
	}
	
	private void addTunnelEntrance(int x1, int y1, int x2, int y2) {
	}
	
	private void removeTunnelEntrance(TunnelEntrance tE) {
	}
	
	private void changeSwitch(Switch s) {
	}
	
	private void removeTrain(Train trainPart) {
	}
	
	private boolean isMapEmpty() {
		return false;
	}
}
