//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Node.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public abstract class Node extends MapItem {

	private Train[] trainsOn;
	private Node nextNode;
	private Node previousNode;

	public void addTrain(Train t) {
	}
	
	public void removeTrain(Train t) {
	}
	
	public Train[] getTrains() {
            Train trains[] = {new Engine(1, 2, 1, 3)};
            Main.tabs++;
            Status temp = Status.NOT_CRASHED;
            System.out.print(">");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("->[:Node].getTrains()\n");
            
            System.out.print("<");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("<-[:Node].getTrains()\n");
            
            Main.tabs--;
		return trains;
	}
	
	public Node getNext() {
            Main.tabs++;
            Status temp = Status.NOT_CRASHED;
            System.out.print(">");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("->[:Node].getNext()\n");
            
            System.out.print("<");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("<-[:Node].getNext()\n");
            
            Main.tabs--;
            return nextNode;
	}
	
	public void setNext(Node n) {
            nextNode = n;
	}
	
	public Node getPrev() {
		return null;
	}
	
	public void setPrev(Node p) {
	}
}
