//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Node.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public abstract class Node extends MapItem {

	private Train[] trainsOn;
	private Node nextNode;
	private Node previousNode;

	public void addTrain(Train t) {
	}
	
	public void removeTrain(Train t) {
	}
	
	public Train[] getTrains() {
		return null;
	}
	
	public Node getNext() {
		return null;
	}
	
	public void setNext(Node n) {
	}
	
	public Node getPrev() {
		return null;
	}
	
	public void setPrev(Node p) {
	}
}
