//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rail.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public class Rail extends Node {

	public Rail(int x, int y, Node n, Node p) {

	}
}
