//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Station.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//


package project;


public class Station extends Node {

	public void Station(int x, int y, Node n, Node p) {

	}
	
	public String getColor(){
		System.out.print(">");
		for(int i = 0; i <= Main.tabs; i++) {
			System.out.print("\t");
		}
		System.out.print("->[:Station].getColor()\n");

		System.out.print("?");
		for(int i = 0; i <= Main.tabs; i++) {
			System.out.print("\t");
		}
		System.out.print("5.2. Milyen színű az állomás? R/Green/B/Y/Gray :");
		char c;
		try{
			c = (char) System.in.read();
			c = (char) System.in.read();
		} catch(Exception e) {
			e.printStackTrace();
		}

		System.out.print("<");
		for(int i = 0; i <= Main.tabs; i++) {
			System.out.print("\t");
		}
		System.out.print("<-[:Station].getColor()\n");

		return null;
	}
}
