//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Station.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//


package project;


public class Station extends Node {

	public void Station(int x, int y, Node n, Node p) {

	}
	
	public String getColor() {
		return null;
	}
}
