//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Switch.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public class Switch extends Node {

	private Node next2Node;

	public Switch(int x, int y, Node n, Node n2, Node p) {
	}
	
	public void changeOutput() {
            System.out.print(">");
            for(int i = 0; i <= Main.tabs; i++) {
                System.out.print("\t");
            }  
            System.out.print("->[:Switch].changeOutput()\n");
            
            System.out.print("<");
            for(int i = 0; i <= Main.tabs; i++) {
                System.out.print("\t");
            }  
            System.out.print("<-[:Switch].changeOutput()\n");
	}
	
	public Node getSecond() {
		return null;
	}
	
	public void setSecond(Node n2) {
	}
}
