//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Switch.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public class Switch extends Node {

	private Node next2Node;

	public void Switch(int x, int y, Node n, Node n2, Node p) {
	}
	
	public void changeOutput() {
	}
	
	public Node getSecond() {
		return null;
	}
	
	public void setSecond(Node n2) {
	}
}
