//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Train.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//


package project;


public abstract class Train extends MapItem {

	private int xEnd;
	private int yEnd;
	private Node onNode;
	private Node prevNode;
	private Car nextCar;

	public Status move() {
            return null;
	}
	
	public int getEndX() {
            Main.tabs++;
            Status temp = Status.NOT_CRASHED;
            System.out.print(">");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("->[:Train].getEndX()\n");

            System.out.print("<");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("<-[:Train].getEndX()\n");
            
            Main.tabs--;
            return 0;
	}
	
	public int getEndY() {
            Main.tabs++;
            Status temp = Status.NOT_CRASHED;
            System.out.print(">");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("->[:Train].getEndY()\n");

            System.out.print("<");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("<-[:Train].getEndY()\n");
            
            Main.tabs--;
            return 0;
	}
	
	public Node getOnNode() {
            Main.tabs++;
            Status temp = Status.NOT_CRASHED;
            System.out.print(">");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("->[:Node].getOnNode()\n");

            System.out.print("<");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("<-[:Node].getOnNode()\n");
            
            Main.tabs--;
            return onNode;
	}
	
	public void setOnNode(Node n) {
            onNode = n;
	}
	
	public Node getPrevNode() {
            return null;
	}
	
	public void setPrevNode(Node p) {
	}
	
	public Car getNextCar() {
            Main.tabs++;
            Status temp = Status.NOT_CRASHED;
            System.out.print(">");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("->[:Train].getNextCar()\n");
            
            
            System.out.print("<");
            for(int i = 0; i < Main.tabs; i++) {
                System.out.print("\t");
            }
            System.out.print("<-[:Train].getNextCar()\n");
            
            Main.tabs--;
            
            return nextCar;
	}
	
	public void setNextCar(Car c) {
            nextCar = c;
	}
	
	public String getColor() {
            return null;
	}
}
