//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Train.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//


package project;


public abstract class Train extends MapItem {

	private int xEnd;
	private int yEnd;
	private Node onNode;
	private Node prevNode;
	private Car nexCar;

	public Status move() {
		return null;
	}
	
	public int getEndX() {
		return 0;
	}
	
	public int getEndY() {
		return 0;
	}
	
	public Node getOnNode() {
		return null;
	}
	
	public void setOnNode(Node n) {
	}
	
	public Node getPrevNode() {
		return null;
	}
	
	public void setPrevNode(Node p) {
	}
	
	public Car getNextCar() {
		return null;
	}
	
	public void setNextCar(Car c) {
	}
	
	public String getColor() {
		return null;
	}
}
