//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Train.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//


package project;


public abstract class Train extends MapItem {

	private int xEnd;
	private int yEnd;
	private Node onNode;
	private Node prevNode;
	private Car nexCar;

	public Status move() {
		return null;
	}
	
	public int getEndX() {
		return 0;
	}
	
	public int getEndY() {
		return 0;
	}
	
	public Node getOnNode() {
		return null;
	}
	
	public void setOnNode(Node n) {
	}
	
	public Node getPrevNode() {
		return null;
	}
	
	public void setPrevNode(Node p) {
	}
	
	public Car getNextCar() {
		return null;
	}
	
	public void setNextCar(Car c) {
	}
	
	public String getColor() {
		System.out.print(">");
		for(int i = 0; i <= Main.tabs; i++) {
			System.out.print("\t");
		}
		System.out.print("->[:Car].getColor()\n");

		System.out.print("?");
		for(int i = 0; i <= Main.tabs; i++) {
			System.out.print("\t");
		}
		System.out.print("5.1. Milyen színű a vagon? R/Green/B/Y/Gray :");
		char c;
		try{
			c = (char) System.in.read();
		} catch(Exception e) {
			e.printStackTrace();
		}

		System.out.print("<");
		for(int i = 0; i <= Main.tabs; i++) {
			System.out.print("\t");
		}
		System.out.print("<-[:Car].getColor()\n");

		return null;
	}
}
