//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TunnelEntrance.java
//  @ Date : 2017. 03. 17.
//  @ Author : 
//
//

package project;

public class TunnelEntrance extends Switch {

	public TunnelEntrance(int x, int y, Node n, Node n2, Node p) {
		super(x, y, n, n2, p);
	}

	public void TunnelEntrance(int x, int y, Node n, Node n2, Node p) {

	}
}
